### ISSUE TITLE
Data type  problem

### ISSUE THREAD

**Issue by YvonneJXD** [ahmedfgad/FeatureReductionGenetic#2]
Dear ahmedfgad，
    If my data were text, 3,000 pages with 1,000 keywords and divided into six categories, how would it translate to dataset_feature and output in your code

**Comment by ahmedfgad** [comment]
Hi @YvonneJXD,
The **dataset_feature** variable holds a numeric array where the columns refer to the number of elements in the feature vector and the rows represent the samples. The **output** variable holds just a number that corresponds to the class ID.

In your case, the **output** variable could be simply prepared. You have 6 categories and thus there are 6 class labels (0 to 5 for example).

The **dataset_feature** variable requires some sort of work to be created. I am not sure how you could extract **numberic** features from the text file but you should find a way.

Note that I documented how the 2 variables are created in a project available here: https://github.com/ahmedfgad/NumPyANN. This project is documented in this tutorial: https://www.linkedin.com/pulse/artificial-neural-network-implementation-using-numpy-fruits360-gad. Note that the project extracts features from image data not text data.

Let me know if I can be helpful in anyway.

**Comment by YvonneJXD** [comment]
Dear ahmedfgad，
Thank you so much for your reply，I've fixed the data problem, and now I want to ask you about parameter Settings, and I know that sol_per_pop is generally 10-200,  but about the parameters num_parents_mating and num_mutations what's the range?
One more question, some claims that genetic algorithms need to set mutation probability and crossover probability, are these two parameters the same meaning as num_parents_mating and num_mutations in your code?They said the crossover probability was generally 0.25 to 1 and the mutation probability was generally 0.001 to 0.1.
Looking forward to your reply.

**Comment by ahmedfgad** [comment]
Hi @YvonneJXD,

Please to hear from you again.

The 2 questions are related and thus I can give a single answer. As you said, the number of parents selected in the mating pool is selected according to a probability. The same happens when selecting the number of genes in the mutation. My project does not accept the probability but the exact number. Do not worry because both lead to the same result. For example, if there are 10 genes and you want to select half of them, then you can set num_mutations to 5. This means the probability is 0.5.

I cannot say there is a preferred range because it all depend on the experiments you conduct. Some situations I have to set the mutation percentage to something very small like 1% and others might need it to something high like 25%. You can visit this link for more info about the probabilities: http://www.optiwater.com/optiga/ga.html
